// examples/src/components/Footer.tsx
import { motion } from 'motion/react';

export function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="bg-[#0f0f0f] border-t border-[#F97316] py-12 relative overflow-hidden">
      {/* Background Pattern */}
      <div className="absolute inset-0 opacity-5"
        style={{
          backgroundImage: `
            linear-gradient(30deg, transparent 45%, #F97316 45%, #F97316 55%, transparent 55%),
            linear-gradient(-30deg, transparent 45%, #F97316 45%, #F97316 55%, transparent 55%)
          `,
          backgroundSize: '20px 40px'
        }}
      ></div>

      <div className="container mx-auto px-4 relative z-10">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
          {/* Logo & Tagline */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
          >
            <div className="flex items-center gap-2 mb-4">
              <div className="w-2 h-12 bg-[#F97316]"></div>
              <span className="text-3xl tracking-wider">
                BF <span className="text-[#F97316]">META</span> HUB
              </span>
            </div>
            <p className="text-gray-400 mb-4">
              Best loadouts and guides for Battlefield 6
            </p>
            <div className="flex gap-4">
              <motion.a
                href="#"
                whileHover={{ scale: 1.1, color: '#F97316' }}
                className="text-gray-400 hover:text-[#F97316] transition-colors"
              >
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M15.12 5.32H17V2.14A26.11 26.11 0 0 0 14.26 2c-2.72 0-4.58 1.66-4.58 4.7v2.62H6.61v3.56h3.07V22h3.68v-9.12h3.06l.46-3.56h-3.52V7.05c0-1.05.28-1.73 1.76-1.73z"/>
                </svg>
              </motion.a>
              <motion.a
                href="#"
                whileHover={{ scale: 1.1, color: '#F97316' }}
                className="text-gray-400 hover:text-[#F97316] transition-colors"
              >
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zM12 0C8.741 0 8.333.014 7.053.072 2.695.272.273 2.69.073 7.052.014 8.333 0 8.741 0 12c0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98C8.333 23.986 8.741 24 12 24c3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98C15.668.014 15.259 0 12 0zm0 5.838a6.162 6.162 0 1 0 0 12.324 6.162 6.162 0 0 0 0-12.324zM12 16a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm6.406-11.845a1.44 1.44 0 1 0 0 2.881 1.44 1.44 0 0 0 0-2.881z"/>
                </svg>
              </motion.a>
              <motion.a
                href="#"
                whileHover={{ scale: 1.1, color: '#F97316' }}
                className="text-gray-400 hover:text-[#F97316] transition-colors"
              >
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M20.317 4.37a19.791 19.791 0 0 0-4.885-1.515.074.074 0 0 0-.079.037c-.21.375-.444.864-.608 1.25a18.27 18.27 0 0 0-5.487 0 12.64 12.64 0 0 0-.617-1.25.077.077 0 0 0-.079-.037A19.736 19.736 0 0 0 3.677 4.37a.07.07 0 0 0-.032.027C.533 9.046-.32 13.58.099 18.057a.082.082 0 0 0 .031.057 19.9 19.9 0 0 0 5.993 3.03.078.078 0 0 0 .084-.028c.462-.63.874-1.295 1.226-1.994a.076.076 0 0 0-.041-.106 13.107 13.107 0 0 1-1.872-.892.077.077 0 0 1-.008-.128 10.2 10.2 0 0 0 .372-.292.074.074 0 0 1 .077-.01c3.928 1.793 8.18 1.793 12.062 0a.074.074 0 0 1 .078.01c.12.098.246.198.373.292a.077.077 0 0 1-.006.127 12.299 12.299 0 0 1-1.873.892.077.077 0 0 0-.041.107c.36.698.772 1.362 1.225 1.993a.076.076 0 0 0 .084.028 19.839 19.839 0 0 0 6.002-3.03.077.077 0 0 0 .032-.054c.5-5.177-.838-9.674-3.549-13.66a.061.061 0 0 0-.031-.03zM8.02 15.33c-1.183 0-2.157-1.085-2.157-2.419 0-1.333.956-2.419 2.157-2.419 1.21 0 2.176 1.096 2.157 2.42 0 1.333-.956 2.418-2.157 2.418zm7.975 0c-1.183 0-2.157-1.085-2.157-2.419 0-1.333.955-2.419 2.157-2.419 1.21 0 2.176 1.096 2.157 2.42 0 1.333-.946 2.418-2.157 2.418z"/>
                </svg>
              </motion.a>
            </div>
          </motion.div>

          {/* Quick Links */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            viewport={{ once: true }}
          >
            <h3 className="text-xl tracking-wider mb-4 text-[#F97316] uppercase">
              Quick Links
            </h3>
            <nav className="flex flex-col gap-2">
              <a href="#" className="text-gray-400 hover:text-[#F97316] transition-colors uppercase text-sm tracking-wide">
                Home
              </a>
              <a href="#" className="text-gray-400 hover:text-[#F97316] transition-colors uppercase text-sm tracking-wide">
                Meta Loadouts
              </a>
              <a href="#" className="text-gray-400 hover:text-[#F97316] transition-colors uppercase text-sm tracking-wide">
                Weapons
              </a>
              <a href="#" className="text-gray-400 hover:text-[#F97316] transition-colors uppercase text-sm tracking-wide">
                News
              </a>
              <a href="#" className="text-gray-400 hover:text-[#F97316] transition-colors uppercase text-sm tracking-wide">
                Guides
              </a>
            </nav>
          </motion.div>

          {/* Resources */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            viewport={{ once: true }}
          >
            <h3 className="text-xl tracking-wider mb-4 text-[#F97316] uppercase">
              Resources
            </h3>
            <nav className="flex flex-col gap-2">
              <a href="#" className="text-gray-400 hover:text-[#F97316] transition-colors uppercase text-sm tracking-wide">
                About Us
              </a>
              <a href="#" className="text-gray-400 hover:text-[#F97316] transition-colors uppercase text-sm tracking-wide">
                Contact
              </a>
              <a href="#" className="text-gray-400 hover:text-[#F97316] transition-colors uppercase text-sm tracking-wide">
                Privacy Policy
              </a>
              <a href="#" className="text-gray-400 hover:text-[#F97316] transition-colors uppercase text-sm tracking-wide">
                Terms of Service
              </a>
            </nav>
          </motion.div>
        </div>

        {/* Bottom Bar */}
        <div className="border-t border-[#F97316]/30 pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
          <p className="text-gray-500 text-sm text-center md:text-left">
            © {currentYear} BF META HUB. All rights reserved. Not affiliated with EA or DICE.
          </p>
          <div className="flex items-center gap-2 text-sm text-gray-500">
            <span>Made by the community, for the community</span>
          </div>
        </div>
      </div>

      {/* Decorative Corner Elements */}
      <div className="absolute top-0 left-0 w-32 h-32 border-l-2 border-t-2 border-[#F97316]/20"></div>
      <div className="absolute top-0 right-0 w-32 h-32 border-r-2 border-t-2 border-[#F97316]/20"></div>
    </footer>
  );
}

// frontend/src/components/Footer.vue
<template>
  <footer class="bg-gradient-to-b from-bf-darker to-black border-t border-bf-orange relative">
    <!-- Top border effect -->
    <div class="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-bf-orange to-transparent"></div>
    
    <div class="container mx-auto px-4 py-16">
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
        <!-- Logo & Description -->
        <motion.div
          :initial="{ opacity: 0, y: 30 }"
          :while-in-view="{ opacity: 1, y: 0 }"
          :transition="{ duration: 0.6 }"
          class="lg:col-span-1"
        >
          <div class="flex items-center gap-3 mb-6">
            <div class="relative">
              <div class="w-12 h-12 bg-bf-orange flex items-center justify-center relative overflow-hidden">
                <span class="text-black text-2xl tracking-wider z-10">BF</span>
                <div class="absolute inset-0 bg-gradient-to-br from-transparent via-white/20 to-transparent transform -skew-x-12"></div>
              </div>
              <div class="absolute -top-1 -left-1 w-3 h-3 border-l-2 border-t-2 border-bf-orange"></div>
              <div class="absolute -bottom-1 -right-1 w-3 h-3 border-r-2 border-b-2 border-bf-orange"></div>
            </div>
            <div>
              <div class="text-xl tracking-widest leading-none">
                BF <span class="text-bf-orange">META</span> HUB
              </div>
              <div class="text-[10px] text-gray-500 tracking-widest mt-0.5">TACTICAL DATABASE</div>
            </div>
          </div>
          <p class="text-gray-400 text-sm leading-relaxed mb-6">
            Your ultimate resource for Battlefield 6 tactical advantage. 
            Stay ahead of the meta with our expert analysis and community insights.
          </p>
          <div class="flex gap-4">
            <motion.a
              v-for="social in socialLinks"
              :key="social.name"
              :href="social.url"
              :while-hover="{ scale: 1.1, y: -2 }"
              :while-tap="{ scale: 0.9 }"
              class="w-10 h-10 bg-bf-orange/20 border border-bf-orange/30 flex items-center justify-center hover:bg-bf-orange hover:border-bf-orange transition-all group"
            >
              <component :is="social.icon" class="w-5 h-5 text-bf-orange group-hover:text-black transition-colors" />
            </motion.a>
          </div>
        </motion.div>

        <!-- Quick Links -->
        <motion.div
          :initial="{ opacity: 0, y: 30 }"
          :while-in-view="{ opacity: 1, y: 0 }"
          :transition="{ duration: 0.6, delay: 0.1 }"
        >
          <h3 class="text-lg font-heading text-bf-orange mb-6 tracking-widest uppercase">
            Quick Links
          </h3>
          <ul class="space-y-3">
            <li v-for="link in quickLinks" :key="link.name">
              <a
                :href="link.url"
                class="text-gray-400 hover:text-bf-orange transition-colors text-sm tracking-wide flex items-center gap-2 group"
              >
                <div class="w-1 h-1 bg-bf-orange group-hover:w-2 transition-all"></div>
                {{ link.name }}
              </a>
            </li>
          </ul>
        </motion.div>

        <!-- Resources -->
        <motion.div
          :initial="{ opacity: 0, y: 30 }"
          :while-in-view="{ opacity: 1, y: 0 }"
          :transition="{ duration: 0.6, delay: 0.2 }"
        >
          <h3 class="text-lg font-heading text-bf-orange mb-6 tracking-widest uppercase">
            Resources
          </h3>
          <ul class="space-y-3">
            <li v-for="resource in resources" :key="resource.name">
              <a
                :href="resource.url"
                class="text-gray-400 hover:text-bf-orange transition-colors text-sm tracking-wide flex items-center gap-2 group"
              >
                <div class="w-1 h-1 bg-bf-orange group-hover:w-2 transition-all"></div>
                {{ resource.name }}
              </a>
            </li>
          </ul>
        </motion.div>

        <!-- Newsletter -->
        <motion.div
          :initial="{ opacity: 0, y: 30 }"
          :while-in-view="{ opacity: 1, y: 0 }"
          :transition="{ duration: 0.6, delay: 0.3 }"
        >
          <h3 class="text-lg font-heading text-bf-orange mb-6 tracking-widest uppercase">
            Stay Updated
          </h3>
          <p class="text-gray-400 text-sm mb-4">
            Get the latest meta updates and exclusive content delivered to your inbox.
          </p>
          <form @submit.prevent="subscribeNewsletter" class="space-y-3">
            <input
              v-model="email"
              type="email"
              placeholder="Enter your email"
              class="w-full px-4 py-3 bg-bf-medium border border-gray-700 text-white placeholder-gray-500 focus:outline-none focus:border-bf-orange transition-colors text-sm"
              required
            />
            <motion.button
              type="submit"
              :while-hover="{ scale: 1.02 }"
              :while-tap="{ scale: 0.98 }"
              class="w-full px-4 py-3 bg-bf-orange text-black font-heading tracking-widest uppercase hover:bg-[#ea6a0f] transition-colors text-sm"
            >
              Subscribe
            </motion.button>
          </form>
        </motion.div>
      </div>

      <!-- Bottom Section -->
      <motion.div
        :initial="{ opacity: 0, y: 20 }"
        :while-in-view="{ opacity: 1, y: 0 }"
        :transition="{ duration: 0.6, delay: 0.4 }"
        class="mt-12 pt-8 border-t border-gray-800"
      >
        <div class="flex flex-col md:flex-row justify-between items-center gap-4">
          <p class="text-gray-500 text-sm">
            © 2024 BF Meta Hub. All rights reserved. Not affiliated with Electronic Arts.
          </p>
          <div class="flex gap-6 text-sm">
            <a href="#" class="text-gray-500 hover:text-bf-orange transition-colors">Privacy Policy</a>
            <a href="#" class="text-gray-500 hover:text-bf-orange transition-colors">Terms of Service</a>
            <a href="#" class="text-gray-500 hover:text-bf-orange transition-colors">Contact</a>
          </div>
        </div>
      </motion.div>
    </div>
  </footer>
</template>

<script setup>
import { ref } from 'vue'
import { motion } from '@vueuse/motion'
import { 
  Twitter, 
  Youtube, 
  Discord, 
  Github, 
  Mail,
  ExternalLink
} from 'lucide-vue-next'

const email = ref('')

const socialLinks = [
  { name: 'Twitter', icon: Twitter, url: '#' },
  { name: 'YouTube', icon: Youtube, url: '#' },
  { name: 'Discord', icon: Discord, url: '#' },
  { name: 'GitHub', icon: Github, url: '#' }
]

const quickLinks = [
  { name: 'Meta Loadouts', url: '#loadouts' },
  { name: 'Weapon Database', url: '#weapons' },
  { name: 'Latest News', url: '#news' },
  { name: 'Tactical Guides', url: '#guides' },
  { name: 'Community', url: '#community' },
  { name: 'Leaderboards', url: '#leaderboards' }
]

const resources = [
  { name: 'Patch Notes', url: '#patches' },
  { name: 'Weapon Stats', url: '#stats' },
  { name: 'Map Guides', url: '#maps' },
  { name: 'Class Builds', url: '#classes' },
  { name: 'Video Tutorials', url: '#tutorials' },
  { name: 'API Documentation', url: '#api' }
]

const subscribeNewsletter = () => {
  if (email.value) {
    // Handle newsletter subscription
    console.log('Subscribing email:', email.value)
    email.value = ''
    // You can add actual subscription logic here
  }
}
</script>
