// examples/src/components/NewsSection.tsx
import { motion } from 'motion/react';
import { Calendar, ArrowRight } from 'lucide-react';
import { ImageWithFallback } from './figma/ImageWithFallback';

const newsArticles = [
  {
    id: 1,
    title: "Season 3 Patch Notes Released",
    summary: "Major weapon balance changes, new maps, and operator updates hit the battlefield this week.",
    date: "October 15, 2025",
    category: "Update",
    tag: "NEW",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0YWN0aWNhbCUyMG1pbGl0YXJ5JTIwaGVsaWNvcHRlcnxlbnwxfHx8fDE3NjA2OTkzNTV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    featured: true
  },
  {
    id: 2,
    title: "Assault Rifle Meta Shift",
    summary: "The M4A1 receives buffs while AK variants see minor nerfs in latest balance update.",
    date: "October 12, 2025",
    category: "Balance",
    tag: "HOT",
    image: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzb2xkaWVyJTIwZXF1aXBtZW50JTIwZ2VhcnxlbnwxfHx8fDE3NjA2OTkzNTV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    featured: false
  },
  {
    id: 3,
    title: "New Limited-Time Event",
    summary: "Operation: Desert Storm brings exclusive rewards and challenging missions to complete.",
    date: "October 10, 2025",
    category: "Event",
    tag: "LIVE",
    image: "https://images.unsplash.com/photo-1579003593419-98f949b9398f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaWxpdGFyeSUyMGJhc2UlMjBhY3Rpb258ZW58MXx8fHwxNzYwNjk5MzU1fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    featured: false
  },
  {
    id: 4,
    title: "Community Tournament Finals",
    summary: "Watch the best teams compete for $50,000 prize pool this weekend.",
    date: "October 8, 2025",
    category: "Esports",
    tag: "TRENDING",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWFtJTIwbWlsaXRhcnl8ZW58MXx8fHwxNzYwNjk4MDE1fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    featured: false
  }
];

const categoryColors = {
  Update: "bg-blue-500/20 text-blue-400 border-blue-400/50",
  Balance: "bg-[#F97316]/20 text-[#F97316] border-[#F97316]/50",
  Event: "bg-purple-500/20 text-purple-400 border-purple-400/50",
  Esports: "bg-green-500/20 text-green-400 border-green-400/50"
};

const tagColors = {
  NEW: "bg-[#F97316] text-black",
  HOT: "bg-red-500 text-white",
  LIVE: "bg-green-500 text-black",
  TRENDING: "bg-yellow-500 text-black"
};

export function NewsSection() {
  return (
    <section id="news" className="py-20 bg-[#1a1a1a] relative overflow-hidden">
      {/* Background Pattern */}
      <div 
        className="absolute inset-0 opacity-5"
        style={{
          backgroundImage: `
            repeating-linear-gradient(45deg, #F97316 0px, #F97316 1px, transparent 1px, transparent 20px),
            repeating-linear-gradient(-45deg, #F97316 0px, #F97316 1px, transparent 1px, transparent 20px)
          `
        }}
      ></div>

      <div className="container mx-auto px-4 relative z-10">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
          className="mb-12"
        >
          <div className="flex items-center justify-between flex-wrap gap-4">
            <div className="text-center md:text-left flex-1">
              <motion.div
                className="w-16 h-1 bg-[#F97316] mx-auto md:mx-0 mb-4"
                initial={{ width: 0 }}
                whileInView={{ width: 64 }}
                transition={{ duration: 0.8 }}
                viewport={{ once: true }}
              />
              <h2 className="text-4xl md:text-5xl tracking-wider mb-3">
                LATEST <span className="text-[#F97316]">NEWS</span>
              </h2>
              <p className="text-gray-400">Stay updated with patches, events, and community highlights</p>
            </div>
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              className="flex items-center gap-2 px-6 py-3 border-2 border-[#F97316] text-[#F97316] hover:bg-[#F97316] hover:text-black transition-colors uppercase tracking-widest text-sm"
            >
              View All
              <ArrowRight className="w-4 h-4" />
            </motion.button>
          </div>
        </motion.div>

        {/* News Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Featured Article */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="lg:row-span-2"
          >
            <div className="group cursor-pointer bg-[#2a2a2a] border-2 border-[#F97316]/30 overflow-hidden h-full relative hover:border-[#F97316] transition-all duration-300">
              {/* Image */}
              <div className="relative h-96 lg:h-full overflow-hidden">
                <ImageWithFallback
                  src={newsArticles[0].image}
                  alt={newsArticles[0].title}
                  className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black via-black/50 to-transparent"></div>
                
                {/* Tag Badge */}
                <div className="absolute top-4 left-4 flex items-center gap-2">
                  <motion.div
                    className={`px-3 py-1 ${tagColors[newsArticles[0].tag as keyof typeof tagColors]} uppercase tracking-wider text-xs`}
                    animate={{
                      scale: [1, 1.05, 1]
                    }}
                    transition={{
                      duration: 1.5,
                      repeat: Infinity
                    }}
                  >
                    {newsArticles[0].tag}
                  </motion.div>
                  <div className={`px-3 py-1 border ${categoryColors[newsArticles[0].category as keyof typeof categoryColors]} uppercase tracking-wider text-xs`}>
                    {newsArticles[0].category}
                  </div>
                </div>

                {/* Content Overlay */}
                <div className="absolute bottom-0 left-0 right-0 p-8">
                  <h3 className="text-3xl md:text-4xl tracking-wide mb-4 text-white group-hover:text-[#F97316] transition-colors">
                    {newsArticles[0].title}
                  </h3>
                  <p className="text-gray-300 mb-4 leading-relaxed">
                    {newsArticles[0].summary}
                  </p>
                  <div className="flex items-center gap-2 text-sm text-gray-400">
                    <Calendar className="w-4 h-4 text-[#F97316]" />
                    <span>{newsArticles[0].date}</span>
                  </div>
                </div>

                {/* Corner Accent */}
                <div className="absolute top-0 right-0 w-16 h-16 border-r-2 border-t-2 border-[#F97316]/50"></div>
              </div>

              {/* Hover indicator */}
              <motion.div
                className="absolute bottom-8 right-8 w-12 h-12 border-2 border-[#F97316] flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity"
                whileHover={{ scale: 1.1, rotate: 90 }}
              >
                <ArrowRight className="w-6 h-6 text-[#F97316]" />
              </motion.div>
            </div>
          </motion.div>

          {/* Secondary Articles */}
          {newsArticles.slice(1).map((article, index) => (
            <motion.div
              key={article.id}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              viewport={{ once: true }}
              whileHover={{ y: -5 }}
            >
              <div className="group cursor-pointer bg-[#2a2a2a] border-2 border-[#F97316]/20 overflow-hidden h-full hover:border-[#F97316] transition-all duration-300 flex flex-col md:flex-row">
                {/* Image */}
                <div className="relative md:w-48 h-48 md:h-auto overflow-hidden flex-shrink-0">
                  <ImageWithFallback
                    src={article.image}
                    alt={article.title}
                    className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700"
                  />
                  <div className="absolute inset-0 bg-gradient-to-r from-transparent to-black/50"></div>
                  
                  {/* Tag */}
                  <div className={`absolute top-2 left-2 px-2 py-1 ${tagColors[article.tag as keyof typeof tagColors]} uppercase tracking-wider text-[10px]`}>
                    {article.tag}
                  </div>
                </div>

                {/* Content */}
                <div className="p-6 flex flex-col justify-between flex-grow">
                  <div>
                    <div className={`inline-block px-2 py-1 border ${categoryColors[article.category as keyof typeof categoryColors]} uppercase tracking-wider text-xs mb-3`}>
                      {article.category}
                    </div>
                    <h3 className="text-xl tracking-wide mb-2 text-white group-hover:text-[#F97316] transition-colors">
                      {article.title}
                    </h3>
                    <p className="text-gray-400 text-sm leading-relaxed mb-4">
                      {article.summary}
                    </p>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2 text-xs text-gray-500">
                      <Calendar className="w-3 h-3 text-[#F97316]" />
                      <span>{article.date}</span>
                    </div>
                    <motion.div
                      whileHover={{ x: 5 }}
                      className="text-[#F97316]"
                    >
                      <ArrowRight className="w-5 h-5" />
                    </motion.div>
                  </div>
                </div>

                {/* Decorative corner */}
                <div className="absolute bottom-0 left-0 w-0 h-0 border-l-[20px] border-l-[#F97316] border-t-[20px] border-t-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
              </div>
            </motion.div>
          ))}
        </div>


      </div>

      {/* Bottom Line */}
      <div className="absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-[#F97316] to-transparent"></div>
    </section>
  );
}

// frontend/src/components/NewsSection.vue
<template>
  <section id="news" class="py-20 bg-gradient-to-b from-bf-darker to-bf-dark relative">
    <!-- Top border effect -->
    <div class="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-bf-orange to-transparent"></div>
    
    <div class="container mx-auto px-4">
      <!-- Section Header -->
      <motion.div
        :initial="{ opacity: 0, y: 30 }"
        :while-in-view="{ opacity: 1, y: 0 }"
        :transition="{ duration: 0.8 }"
        class="text-center mb-16"
      >
        <div class="flex items-center justify-center gap-4 mb-6">
          <div class="w-16 h-1 bg-bf-orange"></div>
          <h2 class="text-4xl md:text-5xl font-heading tracking-widest text-bf-orange uppercase">
            Latest News
          </h2>
          <div class="w-16 h-1 bg-bf-orange"></div>
        </div>
        <p class="text-gray-400 text-lg tracking-wide">
          Stay updated with the latest Battlefield 6 news and updates
        </p>
      </motion.div>

      <!-- News Grid -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        <motion.article
          v-for="(article, index) in newsArticles"
          :key="article.id"
          :initial="{ opacity: 0, y: 50 }"
          :while-in-view="{ opacity: 1, y: 0 }"
          :transition="{ duration: 0.6, delay: index * 0.1 }"
          class="group cursor-pointer"
          :while-hover="{ y: -10, scale: 1.02 }"
        >
          <div class="bg-gradient-to-br from-bf-medium to-bf-light border border-gray-800 rounded-lg overflow-hidden transition-all duration-300 group-hover:border-bf-orange group-hover:shadow-2xl group-hover:shadow-bf-orange/20">
            <!-- Article Image -->
            <div class="relative h-48 overflow-hidden">
              <img
                :src="article.image"
                :alt="article.title"
                class="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110"
              />
              <div class="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"></div>
              <div class="absolute top-4 left-4">
                <span class="px-3 py-1 bg-bf-orange text-black text-xs font-bold tracking-widest uppercase rounded">
                  {{ article.category }}
                </span>
              </div>
              <div class="absolute bottom-4 left-4 text-white text-sm">
                {{ formatDate(article.date) }}
              </div>
            </div>

            <!-- Article Content -->
            <div class="p-6">
              <h3 class="text-xl font-heading text-white mb-3 group-hover:text-bf-orange transition-colors">
                {{ article.title }}
              </h3>
              <p class="text-gray-400 text-sm leading-relaxed mb-4">
                {{ article.excerpt }}
              </p>
              <div class="flex items-center justify-between">
                <span class="text-bf-orange text-sm font-medium tracking-wide">
                  Read More →
                </span>
                <div class="flex items-center gap-2 text-gray-500 text-xs">
                  <Clock class="w-4 h-4" />
                  {{ article.readTime }} min read
                </div>
              </div>
            </div>
          </div>
        </motion.article>
      </div>

      <!-- View All Button -->
      <motion.div
        :initial="{ opacity: 0, y: 30 }"
        :while-in-view="{ opacity: 1, y: 0 }"
        :transition="{ duration: 0.6, delay: 0.3 }"
        class="text-center mt-12"
      >
        <motion.button
          :while-hover="{ scale: 1.05 }"
          :while-tap="{ scale: 0.95 }"
          class="px-8 py-4 border-2 border-bf-orange bg-transparent text-bf-orange hover:bg-bf-orange hover:text-black transition-all duration-300 font-heading tracking-widest uppercase"
        >
          View All News
        </motion.button>
      </motion.div>
    </div>
  </section>
</template>

<script setup>
import { ref } from 'vue'
import { motion } from '@vueuse/motion'
import { Clock } from 'lucide-vue-next'

const newsArticles = ref([
  {
    id: 1,
    title: 'Major Weapon Balance Update',
    excerpt: 'Significant changes to weapon damage, recoil patterns, and attachment effectiveness in the latest patch.',
    image: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop',
    category: 'Update',
    date: new Date('2024-01-15'),
    readTime: 5
  },
  {
    id: 2,
    title: 'New Map: Urban Warfare',
    excerpt: 'Experience intense close-quarters combat in the newly added urban environment with destructible buildings.',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop',
    category: 'Map',
    date: new Date('2024-01-12'),
    readTime: 3
  },
  {
    id: 3,
    title: 'Weekend Double XP Event',
    excerpt: 'Earn double experience points for all activities this weekend. Perfect time to level up your weapons and classes.',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop',
    category: 'Event',
    date: new Date('2024-01-10'),
    readTime: 2
  },
  {
    id: 4,
    title: 'Pro Player Meta Analysis',
    excerpt: 'Top professional players share their insights on the current meta and optimal loadout strategies.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop',
    category: 'Analysis',
    date: new Date('2024-01-08'),
    readTime: 7
  },
  {
    id: 5,
    title: 'New Vehicle Customization',
    excerpt: 'Unlock new vehicle skins, modifications, and special abilities in the latest content update.',
    image: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=300&fit=crop',
    category: 'Content',
    date: new Date('2024-01-05'),
    readTime: 4
  },
  {
    id: 6,
    title: 'Community Tournament Results',
    excerpt: 'Check out the highlights and results from our latest community tournament featuring the best players.',
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=300&fit=crop',
    category: 'Tournament',
    date: new Date('2024-01-03'),
    readTime: 6
  }
])

const formatDate = (date) => {
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  })
}
</script>
